- hosts: walters-f20-atomic-local
  sudo: yes

  vars:
    datadir: /srv/fedora-atomic
    outputdir: "{{ datadir }}/output"
    inboxdir: /srv/fedora-atomic/inbox

  tasks:
    - name: add f21 repo
      action: copy src=files/fedora-21.repo
              dest=/etc/yum.repos.d/fedora-21.repo
              owner=root group=root

    - yum: name={{ item }} state=present
      with_items:
        - mock
        - fedora-release-rawhide

    - yum: name={{ item }} state=latest enablerepo=rawhide
      with_items:
        - git
        - ostree
        - rpm-ostree-toolbox

    - command: grep -q 10.88.88 /etc/libvirt/qemu/networks/default.xml
      register: libvirt_is_10_88
      ignore_errors: True

    - service: name=libvirtd state=stopped
      when: libvirt_is_10_88|failed

    - name: Change libvirt default network to 10.88.88
      action: copy src=files/libvirt-network.xml
              dest=/etc/libvirt/qemu/networks/default.xml
              mode=0644
      when: libvirt_is_10_88|failed

    - service: name=libvirtd state=started
      when: libvirt_is_10_88|failed

    - file: path={{ inboxdir }}
            owner=root group=rpmostreecompose mode=755 state=directory

    - file: path={{ outputdir }}/repo
            owner=root group=root mode=755 state=directory

    - command: /usr/bin/ostree init --repo={{ outputdir }}/repo --mode=archive-z2
      args:
        creates: "{{ outputdir }}/repo/objects"
